#Screen presets
WIDTH = 600
HEIGHT = 600
BACKGROUND_COLOR = (0, 0, 0)
X_MIN = -450
X_MAX = 450
Y_MIN = -450
Y_MAX = 450


#Simulation presets
PARALEL_PROCESSES_USED = 10
EXAMPLE_NUMBER = 3
PRESERVE_SPEED = True            #if True preserves speed otherwise preserves delta time
ORIGINAL_SPEED = 1
ORIGINAL_DELTA_TIME = 0.001
CAMERA_SPEED = 0.4
SCALING_SPEED = 0.1
SPEED_CHANGING_SPEED = 1
SPEED_CHANGING_DELTA_TIME = 0.001